NDefines.NOperatives.MAX_RECRUITED_OPERATIVES = 50
NDefines.NBuildings.MAX_BUILDING_LEVELS = 50
NDefines.NBuildings.MAX_SHARED_SLOTS = 50
NDefines.NCountry.POLITICAL_POWER_LOWER_CAP = -4000.0
NDefines.NCountry.POLITICAL_POWER_UPPER_CAP = 5000.0
NDefines.NCountry.VOLUNTEERS_DIVISIONS_REQUIRED = 5